import { graphql } from '@/gql';

/**
 * The single query the application issues. Every filter is passed as a
 * variable so the database - not the browser - decides which rows come back.
 *
 * `graphql()` is generated by the codegen client preset; it returns a
 * `TypedDocumentNode`, which is what gives `execute()` its result typing.
 */
export const CharactersQuery = graphql(`
  query Characters($filter: CharacterFilterInput) {
    characters(filter: $filter) {
      id
      name
      image
      status
      gender
      description
    }
  }
`);
