'use client';

import { keepPreviousData } from '@tanstack/react-query';
import { useQueryStates } from 'nuqs';

import { useCharactersQuery } from '@/gql/graphql';
import { useDebouncedValue } from '@/hooks/use-debounced-value';

import {
  characterSearchParams,
  characterSearchParamsOptions,
} from './search-params';

const SEARCH_DEBOUNCE_MS = 300;

/**
 * Connects URL state to the server.
 *
 * The flow is: control -> nuqs writes the URL -> the search term is debounced ->
 * the variables change -> the generated hook's queryKey changes -> React Query
 * refetches -> the backend filters in PostgreSQL. Nothing is filtered here.
 *
 * `useCharactersQuery` is generated by GraphQL Codegen from
 * characters.graphql; this hook only supplies the variables and adapts the
 * result for the UI.
 */
export function useCharacters() {
  const [filters, setFilters] = useQueryStates(
    characterSearchParams,
    characterSearchParamsOptions,
  );

  // Only the free-text input needs debouncing; picking from a dropdown is a
  // deliberate, low-frequency action and should feel immediate.
  const debouncedSearch = useDebouncedValue(filters.search, SEARCH_DEBOUNCE_MS);

  const query = useCharactersQuery(
    {
      filter: {
        search: debouncedSearch.trim() || null,
        status: filters.status,
        gender: filters.gender,
      },
    },
    {
      // React Query v5 replaced `keepPreviousData: true` with this. It keeps
      // the previous results on screen while the next set loads, so changing a
      // filter does not blank the grid.
      placeholderData: keepPreviousData,
    },
  );

  const hasActiveFilters = Boolean(
    filters.search || filters.status || filters.gender,
  );

  const resetFilters = () =>
    setFilters({ search: '', status: null, gender: null });

  return {
    filters,
    setFilters,
    resetFilters,
    hasActiveFilters,
    characters: query.data?.characters ?? [],
    isLoading: query.isLoading,
    isError: query.isError,
    error: query.error,
    refetch: query.refetch,
    // True while showing the previous filter's results during a refetch - used
    // to dim the grid instead of unmounting it.
    isStale: query.isPlaceholderData && query.isFetching,
    // The user has typed something the server has not been asked about yet.
    isTypingAhead: filters.search !== debouncedSearch,
  };
}
